import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Root Page",
  description: "Generated by create next app",
};

export default function Home() {
  console.log(process.env);
  return <h1>/app/page.tsx [Gitlab deploy]</h1>;
}
