import { Metadata } from "next";

export const metadata: Metadata = {
  title: "Profile Page",
  description: "Generated by create next app",
};

const ProfilePage = () => {
  return (
    <>
      <h1>/app/profile/page.tsx</h1>
    </>
  );
};
export default ProfilePage;
